# ============================================================
#  Gradle 构建参数（私有相册 App）
# ============================================================
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.configureondemand=false

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true

# 关键：允许项目路径包含非 ASCII 字符（本工程路径 F:\安卓测试 含中文）
android.overridePathCheck=true

# 关闭构建分析/遥测上报（本机网络受限）
android.suppressUnsupportedCompileSdk=36
